name: Readme Generator
on:
  schedule: [{ cron: '0 0 * * *' }]
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Left
        uses: lowlighter/metrics@latest
        with:
          filename: assets/left.svg
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, starts, achievements
          plugin_isocalendar: yes
          plugin_stars: yes
          plugin_stars_limit: 3
          plugin_achievements: yes
          plugin_achievements_display: detailed  # compact also available
          plugin_achievements_threshold: S
          token: ${{ secrets.METRICS_TOKEN }}

      - name: Right
        uses: lowlighter/metrics@latest
        with:
          config_order: anilist
          filename: assets/right.svg
          base: ''
          plugin_anilist_user: 'TaurusSilver1'
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit: 3
          plugin_anilist_limit_characters: 30
          plugin_anilist_shuffle: yes
          token: ${{ secrets.METRICS_TOKEN }}

          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}


