name: Update Image Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 1 UTC everyday
    - cron: "*/1 * * * *"

jobs:
  update-readme:
    name: Update Image README
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/update-readme-image@main
        with:
          HEIGHT: 90%       # default
          WIDTH: 90%        # default
          ALIGN: center        # default
          IMG_ALT: Image ALT #image alt to be displayed if image is not mapped correctly
